# Generated by Django 3.2.9 on 2022-05-18 19:56

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authnapp', '0003_auto_20220518_2250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopuser',
            name='activation_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 20, 19, 56, 31, 775989, tzinfo=utc), verbose_name='актуальность ключа'),
        ),
    ]
