# Generated by Django 3.2.9 on 2022-05-18 20:22

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authnapp', '0004_alter_shopuser_activation_key_expires'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopuser',
            name='activation_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 20, 20, 22, 13, 663238, tzinfo=utc), verbose_name='актуальность ключа'),
        ),
    ]
